routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/', function () {
        return redirect()->route('childrens.index');
    })->name('dashboard');


});



Route::namespace('App\Http\Controllers')->group(function() {
    Route::get('/childrens/status-change', 'ChildrensController@ChangeStatus')->name('childrens.ChangeStatus');
    Route::get('/childrens/unenroll', 'ChildrensController@unenroll')->name('childrens.unenroll');
    Route::resource('/childrens', 'ChildrensController');
    Route::resource('/classes', 'ClassesController');
});

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SchoolClass;

class ClassesController extends Controller
{
    public function index(Request $request)
    {
        $data['classes'] = SchoolClass::with('childrens')->latest()->paginate(10)->withQueryString();
        return view('classes.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('classes.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required|alpha|max:300',
            'seat'     => 'required',
            'description'   => 'required',
        ]);

        $data = $request->except('_token');
        $class = SchoolClass::create($data);

        // notify()->success('Class add successfully');
        return redirect()->route('classes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['class'] = SchoolClass::with('childrens')->find(base64_decode($id));
        return view('classes.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['class'] = SchoolClass::find(base64_decode($id));
        return view('classes.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'    => 'required',
            'seat'     => 'required',
            'description'   => 'required',
        ]);

        $class = SchoolClass::find($id);

        $data = $request->except(['_method', '_token']);


        $class->update($data);


        // notify()->success('Class successfully updated');
        return redirect()->route('classes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $class = SchoolClass::find(base64_decode($id));
        $class->delete();
        // notify()->success('Class successfully deleted');
        return back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/classes/form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        @php
            $name = isset($class) ? "Update": "Add";
        @endphp
            {{ __($name.' class') }}
        </h2>
        <div class="col-12 text-right">
            <a class="btn btn-primary btn-sm" href="{{ route('classes.index') }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
            </a>
        </div>
    </x-slot>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
    <!-- Page content -->

            <div class="card-body">
                @php
                 $action = isset($class) ? route('classes.update', [$class->id]) : route('classes.store');
                @endphp
                <form class="form" method="post" action="{{ $action }}" enctype="multipart/form-data">
                    @if (isset($class)) @method('PUT') @endif
                    @csrf
                    <div class="">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-control-label required" for="input-first-name">Name</label>
                                    <input type="text" id="input-first-name" name="name" class="form-control" placeholder="Name" value="{{ old('name', $class->name ?? '') }}" required>
                                    @error('name')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            {{-- <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label required" for="input-first-name">Seats</label>
                                    <input type="number" min="0" max="4" id="input-first-name" name="seat" class="form-control" placeholder="Seats" value="{{ old('seat', $class->seat ?? '') }}" required>
                                    @error('seat')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div> --}}
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-control-label required" for="input-first-name">Description</label>
                                    <input type="text" id="input-first-name" name="description" class="form-control" placeholder="Description" value="{{ old('description', $class->description ?? '') }}" required>
                                    @error('description')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                    </div>
                    <x-jet-button class="mt-4 text-center">Submit
                    </x-jet-button>
                    <input type="hidden" name="seat" value="4">
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/classes/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Manage Classes') }}
        </h2>
    </x-slot>
    <a href="{{ route('classes.create') }}" class="btn btn-info btn-sm">Add New</a>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                    <!-- Light table -->
            <div class="table-responsive">
                <table class="table custom-table">
                    <thead class="thead-light">
                        <tr class="">
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Seat</th>
                            <th scope="col">Description</th>
                            {{-- <th scope="col">Total Requested Seat</th> --}}
                            <th scope="col" class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @forelse($classes as $index=>$class)
                            <tr>
                                <td> {{ $index + $classes->firstItem() }} </td>
                                <td> {{ $class->name ?? '--' }} </td>
                                <td> {{ 4 - ($class->ChildCount ?? 0) }} </td>
                                <td> {{ $class->description ?? '' }} </td>
                                {{-- <td> {{ $class->requestChildrens() ?? '0' }} </td> --}}
                                <td class="text-center">
                                     {{-- <a href="{{ route('classes.show', [base64_encode($class->id)]) }}" class="btn btn-primary btn-sm">Show</a> --}}
                                    <a href="{{ route('classes.edit', [base64_encode($class->id)]) }}" class="btn btn-primary btn-sm">Edit</a>
                                    <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-confirm" data-form="deleteForm-{{ $class->id }}">Delete</a>
                                    <form id="deleteForm-{{ $class->id }}" action="{{ route('classes.destroy', [base64_encode($class->id)]) }}" method="post">
                                        @csrf @method('DELETE')
                                    </form>
                                </td>
                            </tr>
                        @empty
                        <h2> No data Found </h2>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="8">
                                {{ $classes->withQueryString()->links() }}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    </x-app-layout>

resources/views/classes/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ $class->name }} Information
        </h2>
        <div class="col-12 text-right">
            <a class="btn btn-primary btn-sm" href="{{ route('classes.index') }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
            </a>
        </div>
    </x-slot>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
    <!-- Page content -->

            <div class="card-body">
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3" for="input-name">Name:</label>
                                    <div class="col-md-9">
                                        {{ $class->name }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Seat:</label>
                                    <div class="col-md-9">
                                        {{ $class->seat ?? '' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Description:</label>
                                    <div class="col-md-9">
                                        {{ $class->description ?? '' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Childrens:</label>
                                    <div class="col-md-9">
                                        @foreach($class->childrens as $children)
                                            {{ $children->name ?? '' }},
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>