routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/', function () {
        return redirect()->route('childrens.index');
    })->name('dashboard');


});



Route::namespace('App\Http\Controllers')->group(function() {
    Route::get('/childrens/status-change', 'ChildrensController@ChangeStatus')->name('childrens.ChangeStatus');
    Route::get('/childrens/unenroll', 'ChildrensController@unenroll')->name('childrens.unenroll');
    Route::resource('/childrens', 'ChildrensController');
    Route::resource('/classes', 'ClassesController');
});

app/Models/Children.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Children extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function parent()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function class()
    {
        return $this->belongsTo(SchoolClass::class,'class_id');
    }
}

app/Http/Controllers/ChildrensController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Children;
use App\Models\SchoolClass;
use Auth;

class ChildrensController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['childrens'] = Children::latest()->paginate(10)->withQueryString();
        return view('childrens.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['classes'] = SchoolClass::get();
        return view('childrens.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required',
            'age'     => 'required|numeric',
            'class_id'     => 'nullable|exists:school_classes,id',
        ]);

        $data = $request->except('_token');
        $data['user_id'] = Auth::id();
        $data['status'] = 1;
        $SchoolClass = SchoolClass::where('id',$request->class_id)->first();
        if($SchoolClass && $SchoolClass->ChildCount >= 4){
            notify()->error('Max 4 seats');
            return redirect()->route('childrens.index');
        }

        $children = Children::create($data);

        // notify()->success('Children add successfully');
        return redirect()->route('childrens.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['children'] = Children::find(base64_decode($id));
        return view('childrens.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['classes'] = SchoolClass::get();
        $data['children'] = Children::find(base64_decode($id));
        return view('childrens.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'    => 'required',
            'age'     => 'required|numeric',
            'class_id'     => 'nullable|exists:school_classes,id',
        ]);

        $children = Children::find($id);

        $data = $request->except(['_method', '_token']);
        $data['user_id'] = Auth::id();

        $children->update($data);


        // notify()->success('Children successfully updated');
        return redirect()->route('childrens.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $children = Children::find(base64_decode($id));
        $children->delete();
        // notify()->success('Children successfully deleted');
        return back();
    }

    public function ChangeStatus(Request $request)
    {
        $children = Children::find($request->children_id);
        if($children){
            $SchoolClass = SchoolClass::where('id',$children->class_id)->first();
            if($SchoolClass && $SchoolClass->seat < $SchoolClass->occupliedChildrens()){
                // notify()->warning('Class seat is Full');
                return 0;
            }
            $children->update(['status' => $request->status]);
            //  notify()->success('Children In Roll successfully ');
             return 1;
        }
        return back();
    }

    public function unenroll(Request $request)
    {
        $children = Children::find(base64_decode($request->children_id));
        if($children){

            $children->update(['class_id' => null]);
            //  notify()->success('Children In Roll successfully ');
            return back();
        }
        return back();
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/childrens/form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        @php
            $name = isset($children) ? "Update": "Add";
        @endphp
            {{ __($name.' Children') }}
        </h2>
        <div class="col-12 text-right">
            <a class="btn btn-primary btn-sm" href="{{ route('childrens.index') }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
            </a>
        </div>
    </x-slot>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
    <!-- Page content -->

            <div class="card-body">
                @php
                 $action = isset($children) ? route('childrens.update', [$children->id]) : route('childrens.store');
                @endphp
                <form class="form" method="post" action="{{ $action }}" enctype="multipart/form-data">
                    @if (isset($children)) @method('PUT') @endif
                    @csrf
                    <div class="">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="form-group">
                                    <label class="form-control-label required" for="input-first-name">Name</label>
                                    <input type="text" id="input-first-name" name="name" class="form-control" placeholder="Name" value="{{ old('name', $children->name ?? '') }}" required>
                                    @error('name')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="form-group">
                                    <label class="form-control-label required" for="input-first-name">Age</label>
                                    <input type="number" min="0" id="input-first-name" name="age" class="form-control" placeholder="Age" value="{{ old('age', $children->age ?? '') }}" required>
                                    @error('age')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-lg-8">
                                <div class="form-group">
                                    <label class="form-control-label ">Enroll in Class</label>
                                    <select  class="form-control" aria-label="User Role" name="class_id">
                                        <option value="" hidden>Select Class</option>
                                        @if(isset($classes) && count($classes))
                                            @foreach ($classes as $class)
                                                <option value="{{ $class->id }}" @if (isset($children) && $children->class_id == $class->id) selected @endif>{{ $class->name ?? ''}}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @error('class_id')
                                        <span class="validation invalid-feedback" role="alert">
                                            <strong>{{ str_replace(' id', '', $message) }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <x-jet-button class="mt-4 text-center">Submit
                    </x-jet-button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/childrens/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Manage Childrens') }}
        </h2>
    </x-slot>
    <a href="{{ route('childrens.create') }}" class="btn btn-info btn-sm">Add New</a>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                    <!-- Light table -->
            <div class="table-responsive">
                <table class="table custom-table">
                    <thead class="thead-light">
                        <tr class="">
                            <th scope="col">#</th>
                            <th scope="col">Parent Name</th>
                            <th scope="col">Name</th>
                            <th scope="col">Age</th>
                            <th scope="col">Class</th>
                            <th scope="col" class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @forelse($childrens as $index=>$children)
                            <tr>
                                <td> {{ $index + $childrens->firstItem() }} </td>
                                <td> {{ $children->parent ? $children->parent->name : '--' }} </td>
                                <td> {{ $children->name ? $children->name : '--' }} </td>
                                <td> {{ $children->age ?? '--' }} </td>
                                {{-- <td >
                                    <input type="button" children-id="{{ $children->id }}" status="{{ ($children->status  == 1) ? 2 : 1 }}" value="{{ ($children->status  == 1) ? 'In Roll' : 'Not In Roll' }}" class="changeStatus  btn btn-{{ ($children->status  == 1) ? 'success' : 'warning' }}" title="Change status to {{ ($children->status  == 1) ? 'Not In Roll' : 'In Roll' }}">
                                </td> --}}
                                <td> {{ ($children->class && $children->class->name) ? $children->class->name : '--' }} </td>

                                <td class="text-center">
                                    @if ($children->class_id)
                                    <a href="{{ route('childrens.unenroll', ["children_id"=> base64_encode($children->id)]) }}" class="btn btn-primary btn-sm">Unenroll</a>
                                    @endif
                                    <a href="{{ route('childrens.edit', [base64_encode($children->id)]) }}" class="btn btn-primary btn-sm">Edit</a>
                                    <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-confirm" data-form="deleteForm-{{ $children->id }}">Delete</a>
                                    <form id="deleteForm-{{ $children->id }}" action="{{ route('childrens.destroy', [base64_encode($children->id)]) }}" method="post">
                                        @csrf @method('DELETE')
                                    </form>
                                </td>
                            </tr>
                        @empty
                        <h2> No data Found </h2>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="8">
                                {{ $childrens->withQueryString()->links() }}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    </x-app-layout>

resources/views/childrens/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ $children->name }} Information
        </h2>
        <div class="col-12 text-right">
            <a class="btn btn-primary btn-sm" href="{{ route('childrens.index') }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
            </a>
        </div>
    </x-slot>
    <!-- Page content -->
    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
    <!-- Page content -->

            <div class="card-body">
                <div class="pl-lg-4">
                    <div class="row">
                    <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3" for="input-name">Parent Name:</label>
                                    <div class="col-md-9">
                                        {{ $children->user ? $children->user->name : '--' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3" for="input-name">Name:</label>
                                    <div class="col-md-9">
                                        {{ $children->name }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Age:</label>
                                    <div class="col-md-9">
                                        {{ $children->age ?? '' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Class:</label>
                                    <div class="col-md-9">
                                        {{ $children->Class->name ?? '' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="row">
                                    <label class="form-control-label col-md-3">Status:</label>
                                    <div class="col-md-9">
                                    {{ ($children->status  == 1) ? 'Not In Roll' : 'In Roll' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>